language: go

sudo: false

go:
- 1.11
- tip

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: skip

notifications:
  email: false

services:
- docker

env:
- DEP_VERSION="0.4.1"

before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

jobs:
  include:
  - stage: test-raport
    script: $HOME/gopath/bin/goveralls -service=travis-ci

  - stage: validation
    script: ./before-commit.sh

# To be provided: needs configuration
#  - stage: push-image
#    script:
#      - docker build -t oauth-less:latest .
#      - docker tag oauth-less:latest mszostok/oauth-less:latest
#      - docker push mszostok/oauth-less:latest
