required = [
  "github.com/golang/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"


[prune]
  go-tests = true
  unused-packages = true
